### ISSUE TITLE
bug: Contributions tab only showing up to 30 and disappearing contributions

### ISSUE THREAD

**Issue by Meng-Heng** [keymanapp/status.keyman.com#410] opened 2023-12-19 04:58 UTC
My understanding is that whenever I have a new contribution, the previous ones get deleted (Mon-Wed) so the total number would stay 30.

![image](https://github.com/keymanapp/status.keyman.com/assets/90595388/f8293f4d-821f-4748-a89f-7556b197f8f4)

Related issue - https://github.com/keymanapp/status.keyman.com/issues/407#event-11255794378

**Comment by mcdurdin** [comment] 2024-01-02 04:30
Closing as duplicate of #407

**Closed by mcdurdin** 2024-01-02 04:30 UTC
Labels: bug, duplicate
